### ISSUE TITLE
Hour Data does not consider start hour and end hour but takes existing data

### ISSUE THREAD

**Issue by pavs94** [valamidev/candlestick-convert#10]
Converting trade data of an hour to candlestick does not consider exact hour values but takes the last existing trade timestamp hence messes up the data.

**Comment by JohannesHoppe** [comment]
Do you have some data to demonstrate that issue?

**Comment by pavs94** [comment]
`
 "data":[
      {
         "time":"1616571098",
         "type":"buy",
         "priceUSD":7.98658475,
         "price":0.00472468,
         "tokenQuantity":1000,
         "total":4.72468089
      },
      {
         "time":"1616570811",
         "type":"buy",
         "priceUSD":7.97349267,
         "price":0.00471714,
         "tokenQuantity":343.99028062,
         "total":1.62264881
      },
      {
         "time":"1616570596",
         "type":"buy",
         "priceUSD":7.96077449,
         "price":0.00470408,
         "tokenQuantity":1986.9054972,
         "total":9.34655883
      },
      {
         "time":"1616569770",
         "type": "sell",
         "priceUSD":7.90000927,
         "price":0.004666,
         "tokenQuantity":200,
         "total":0.9331993
      },
      {
         "time":"1616569175",
         "type":"buy",
         "priceUSD":7.90015335,
         "price":0.00469422,
         "tokenQuantity":180,
         "total":0.84496029
      },
      {
         "time":"1616568966",
         "type":"sell",
         "priceUSD":7.85530358,
         "price":0.00466759,
         "tokenQuantity":450,
         "total":2.10041682
      },
      {
         "time":"1616567194",
         "type":"buy",
         "priceUSD":7.8137139,
         "price":0.00469543,
         "tokenQuantity":500,
         "total":2.34771558
      },
      {
         "time":"1616566479",
         "type":"buy",
         "priceUSD":7.79651502,
         "price":0.00468153,
         "tokenQuantity":2000,
         "total":9.36306341
      },
      {
         "time":"1616565951",
         "type":"buy",
         "priceUSD":7.78329794,
         "price":0.00465888,
         "tokenQuantity":2100,
         "total":9.7836478
      },
      {
         "time":"1616565951",
         "type":"buy",
         "priceUSD":7.75652985,
         "price":0.00464302,
         "tokenQuantity":790,
         "total":3.66798304
      },
      {
         "time":"1616563543",
         "type":"buy",
         "priceUSD":7.73829298,
         "price":0.00463645,
         "tokenQuantity":409.79598278,
         "total":1.9
      },
      {
         "time":"1616562993",
         "type":"sell",
         "priceUSD":7.72067184,
         "price":0.00462276,
         "tokenQuantity":2997.52535943,
         "total":13.85684137
      },
      {
         "time":"1616562348",
         "type":"buy",
         "priceUSD":7.97053339,
         "price":0.00475494,
         "tokenQuantity":5678.30444278,
         "total":27
      }]
`

When I convert this to 1hr OHLC I want it to start from 00:00 and end at 01:00, but that does not happen. it takes start of hour and end of hour timestamps (for priceUSD and time) .

**Comment by valamidev** [comment]
Did u try to using time in `ms` ? This look me standard Unix time: ` "time":"1616571098"`.

**Comment by JohannesHoppe** [comment]
# 🤷‍♂️

**Comment by valamidev** [comment]
The scenario is covered with unit tests:
- https://github.com/valamidev/candlestick-convert/blob/master/__tests__/Tickdata.test.ts
and the sample data ha incompatible time format with the package.

**Comment by JohannesHoppe** [comment]
I am totally with you. If someone raises an issue and a solution is offered, then one should at least confirm if the issue has been resolved or not.
