### ISSUE TITLE
last candle missing after conversion

### ISSUE THREAD

**Issue by ne0c0de** [valamidev/candlestick-convert#11]
Hi

I noticed that when I convert 1m candle data to 5m and doing it rather 4th minute of time, the last candle (actually active candle) is missing

Here's how tp reproduce:

```
let candles = await binance.candles({ symbol: 'STORJUSDT', interval: '1m', limit: 900 })
let m5Candles = batchCandleJSON(candles.map(d => { return {
        time: d.openTime,
        open: d.open,
        high: d.high,
        low: d.low,
        close: d.close,
        volume: d.volume,
    } }), 60, 300)
let b5mcandles = await binance.candles({ symbol: 'STORJUSDT', interval: '5m', limit: 180 })
console.log('m5Candles: ', JSON.stringify(m5Candles.map(d => d.close.toFixed(4)).slice(-3)))
console.log('binance 5mcandles:', JSON.stringify(b5mcandles.map(d => d.close).slice(-3)))
```

if you run these codes for example on 14:41 of the time you can get this kind of data:

```
m5Candles:  ["0.9420","0.9410","0.9455"]
binance 5mcandles: ["0.94100000","0.94550000","0.94380000"]
```

If I change 76th line on index.js

from this:

```
if (j === convertRatio) {
```

to this:

```
if (j === convertRatio || (i == candledata.length - 1)) {
```

it gives me the correct conversation with last candle:

```
m5Candles:  ["0.9410","0.9455","0.9434"]
binance 5mcandles: ["0.94100000","0.94550000","0.94340000"]
```

I don't have enought time to pull your code and make a pull request for this but suggest you apply this fix from your side.

Btw, thanks for the whole library..

**Comment by valamidev** [comment]
It is the behavior of the OpenCandles, on Binance and most of the exchanges the last candle always build on the data from last candle close time.  Which is good for visual representation, but not good for trading.

I did add a new option to `batchCandleArray ` which allow you to create identical candles with Binance.
```
batchCandleArray = (
  candledata: OHLCV[],
  baseFrame: number = 60,
  newFrame: number = 300,
  includeOpenCandle = false
)

**Comment by ne0c0de** [comment]
Actually I would like to follow active live candle and this is why I would like to get last candle too

Your way is better to achieve this. Thanks for you support

**Comment by valamidev** [comment]
New version out with this feature.
