### ISSUE TITLE
How to convert 1m array of data into month candles?

### ISSUE THREAD

**Issue by renatoaraujoc** [valamidev/candlestick-convert#12]
Hello, thank you for your script, very usefull!

Got a question...

Let's say I have 2 months worth of 1m candlestick data, so an array of `2 * <month_days> * 24 * 60 * 60`.

Considering that february has 28 days and march has 31 days and I have an array of all `1m` data for these 2 months, how would I make the function call to transform it to `1M` if months can have different days?

```js
const res = batchCandleJSON(
  candledata,
  60,
  (28|30|31)? * 24 * 60 * 60 
);
```
I would expect `res` to have an array with 2 candlestick values.

Essentially, I'd like to implement this function as well:

```js
function timeframeToSeconds(timeframe: string): number {
  const map = {
    'm': 60,
    'h': 60 * 60,
    'd': 24 * 60 * 60,
    'w': 7 * 24 * 60 * 60,
    'M': ?? * 24 * 60 * 60 // what value to put here?
  };
  const res = timeframe.match(/(?<value>[0-9]+)(?<unit>[mhdwM])/);
  const value = parseInt(res.groups['value']);
  const unit = res.groups['unit'];

  return Object.keys(map).includes(unit) ? value * map[unit] : -1;
}
```
Thanks for the clarification :)

**Comment by valamidev** [comment]
IMO "monthly" candle is always represent 30d in trading, unless it is really used to represent january,february.
