### ISSUE TITLE
Your script does not work alone, why are you posting them?

### ISSUE THREAD

**Issue by izhtrade** [valamidev/candlestick-convert#5]
I checked your two scripts, they do not work in real time, so the last "сlose" does not move

**Comment by izhtrade** [comment]
I checked your two scripts, they do not work in real time, so the last "сlose" does not move

**Comment by ohager** [comment]
@izhtrade https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612 :wink:
