### ISSUE TITLE
Ticks to OHLC: One candle is missing?

### ISSUE THREAD

**Issue by JohannesHoppe** [valamidev/candlestick-convert#8]
Hello,

I am not so familiar with the processing of financial data, so I hope for your patience. I have either not understood the underlying concept or I have found a bug. 😇 

**Demo**
**https://tvjs.io/play?a=hfht2hd0**
The whole example can be found there.

**The data**
I use data from [Uniswap](https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2), every trade is readable. I want to group the raw data by different time frames to be able to display them in a chart. As an example we can take this dead fake-pair:

https://app.astrotools.io/pair-explorer/0x97289c815c495e53ba1fa12c1fdfb61ad6a2867f
https://tools.unimonitor.io/#/pair-explore/0x97289c815c495e53ba1fa12c1fdfb61ad6a2867f
https://www.dextools.io/app/uniswap/pair-explorer/0x97289c815c495e53ba1fa12c1fdfb61ad6a2867f

As you can see, we have 43 trades. The first trades occurred at `2021-02-08T07:16:33.000Z` and the last one was at `2021-02-08T15:06:32.000Z`. If I count the hours in between, I come up with 9 candles for a 1h time frame.

<img width="645" alt="Screen Shot 2021-02-12 at 16 57 38" src="https://user-images.githubusercontent.com/640639/107790827-7b1ad000-6d53-11eb-9e4d-5cdcac28d668.png">

**The problem**

I use the following function:
```
var candles = batchTicksToCandle(swaps, 60 * 60);
```
Unfortunately, I then only get grouped OHLC data with 8 candles. Something must be wrong there. On the other websites shown above, however, you always see 9 candles. Have I used the library incorrectly?

<img width="785" alt="Screen Shot 2021-02-12 at 17 09 02" src="https://user-images.githubusercontent.com/640639/107792202-24ae9100-6d55-11eb-9d8f-7ba1b72d87ba.png">

Here you see 8 candles in my version:

<img width="45%" alt="Screen Shot 2021-02-12 at 17 11 42" src="https://user-images.githubusercontent.com/640639/107792771-ce8e1d80-6d55-11eb-9605-4908b6379cdf.png">

But 9 candles on the other websites:

<img width="45%" align="left" alt="Screen Shot 2021-02-12 at 17 13 03" src="https://user-images.githubusercontent.com/640639/107792807-d9e14900-6d55-11eb-9692-d6c7c3a85ecd.png">
<img width="45%" align="left" alt="Screen Shot 2021-02-12 at 17 13 47" src="https://user-images.githubusercontent.com/640639/107792814-db127600-6d55-11eb-99c3-89adb1176255.png">

<img width="100%" height="1" src="https://user-images.githubusercontent.com/640639/107793932-237e6380-6d57-11eb-8910-8922e88ce699.png">

**I would be very grateful if you could help in any way! Many thanks in adance!** 👍

**Comment by valamidev** [comment]
The reason is, that the last Candle is an open(unfinished) candle 15:00, it is not supported at this moment to create unfinished candles.

**Comment by JohannesHoppe** [comment]
Any chance this feature is on your roadmap? 😉

**Comment by valamidev** [comment]
I will see when I can get some time to implement.
